---
- name: setup control node
  hosts: localhost
  become: yes
  tasks:
    - name: install packages
      dnf:
        name:
          - vim-enhanced
          - vim-minimal
          - git
          - tree
          - libselinux-python
          - unbound
        state: latest
    - name: install powerline
      become: no
      pip:
        name: powerline-status
        executable: pip2
        state: present
        extra_args: "--user"

    - name: add powerline to environment
      lineinfile:
        line: "{{ item }}"
        dest: /home/{{ ansible_user }}/.bashrc
      with_items:
        - export PATH=$PATH:~/.local/bin
        - powerline-daemon -q
        - ". ~/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh"
        
    - name: deploy vimrc
      copy:
        content: |
          set sw=2
          set expandtab
          set tabstop=2
          set softtabstop=2
          set laststatus=2 " Always display the statusline in all windows "
          set showtabline=2 " Always display the tabline, even if there is only one tab "
          set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline) "
          python from powerline.vim import setup as powerline_setup
          python powerline_setup()
          python del powerline_setup
          
        dest: "/home/{{ ansible_user }}/.vimrc"
