---
# defaults file for kubernetes-master
# etcd certificate configuration
# yamllint disable rule:line-length
apiserver_etcd_use_certs: false
kube_etcd_certs_dir: "{{ kube_cert_dir }}/etcd"
apiserver_etcd_ca_file: "{{ kube_etcd_certs_dir }}/ca.crt"
apiserver_etcd_cert_file: "{{ kube_etcd_certs_dir }}/client.crt"
apiserver_etcd_key_file: "{{ kube_etcd_certs_dir }}/client.key"

services_enabled: true
apiserver_modified: false
controller_manager_modified: false
scheduler_modified: false
kubelet_modified: false

# List of Kubernetes binaries to download and install.
kube_client_binaries:
  - kubectl

etcd_client_port: '2379'

kube_apiserver_options:
  - "--tls-cert-file={{ kube_cert_dir }}/apiserver.crt"
  - "--tls-private-key-file={{ kube_cert_dir }}/apiserver.key"
  - "--client-ca-file={{ kube_cert_dir }}/ca.crt"
  - "--token-auth-file={{ kube_token_dir }}/known_tokens.csv"
  - "--service-account-key-file={{ kube_cert_dir }}/apiserver.crt"
  - "--bind-address={{ kube_apiserver_bind_address }}"
  - "--apiserver-count={{ groups['masters']|length }}"

kube_controller_manager_options:
  - "--kubeconfig={{ kube_config_dir }}/controller-manager.kubeconfig"
  - "--service-account-private-key-file={{ kube_cert_dir }}/apiserver.key"
  - "--root-ca-file={{ kube_cert_dir }}/ca.crt"

kube_scheduler_options:
  - "--kubeconfig={{ kube_config_dir }}/scheduler.kubeconfig"

admission_controllers: "NamespaceLifecycle,LimitRanger,ServiceAccount,PodSecurityPolicy,DefaultStorageClass,ResourceQuota,NodeRestriction"

kube_apiserver_additional_options: []
kube_controller_manager_additional_options: []
kube_scheduler_additional_options: []
kube_token_dir: "{{ kube_config_dir }}/tokens"
kube_apiserver_bind_address: "0.0.0.0"
kube_apiserver_insecure_bind_address: "127.0.0.1"
kube_master_api_port: "{{ master_cluster_port }}"
